//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetMeThere.MVC.Models.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class meetmethereEntities : DbContext
    {
        public meetmethereEntities()
            : base("name=meetmethereEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Meeting> Meetings { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<Team_Meeting> Team_Meeting { get; set; }
        public virtual DbSet<Team_User> Team_User { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
