//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetMeThere.MVC.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MontrealPublicPlace
    {
        public int Id { get; set; }
        public Nullable<int> no { get; set; }
        public string lieux_en_activites_ou_construction { get; set; }
        public string arrondissement { get; set; }
        public string noms_du_reseau { get; set; }
        public string nom_du_lieu_culturel_municipal { get; set; }
        public string adresse { get; set; }
        public string public_string_code_postal___get__set___ { get; set; }
        public string ville { get; set; }
        public string province { get; set; }
        public string telephone_general { get; set; }
        public string telephone_secteur_adulte { get; set; }
        public string telephone_secteur_jeunesse { get; set; }
        public string public_string_site_internet___get__set___ { get; set; }
        public string transport { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
    }
}
