//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetMeThere.MVC.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team_Meeting
    {
        public int Id { get; set; }
        public Nullable<int> TeamId { get; set; }
        public Nullable<int> MeetingId { get; set; }
    
        public virtual Meeting Meeting { get; set; }
        public virtual Team Team { get; set; }
    }
}
